### ISSUE TITLE
Add Shimmer effect

### ISSUE THREAD

**Issue by Alpha17-2** [Utopia7017/utopia#58]
- [x] Profile screen
- [x] Explore articles screen
- [x] My Articles screen
- [ ] User Profile Screen ( profile for displaying different user's profile )
- [x] Notification Screen
- [x] Comment screen
- [x] Followers screen
- [x] Following screen
- [x] Blocked users screen
- [x] Recent Articles box

**Comment by SmartAree** [comment]
ohk .. I'll work on this

**Comment by Alpha17-2** [comment]
Sure !!

**Comment by SmartAree** [comment]
I am having an issue.

![error](https://user-images.githubusercontent.com/41040479/194714091-f6eeba2d-e7c0-4ee2-9740-2576aba04cdd.PNG)

**Comment by Alpha17-2** [comment]
Sorry for my late response !! 
Please go through the setup instructions

**Comment by Alpha17-2** [comment]
fixed by #211
