### ISSUE TITLE
Create onboarding screen

### ISSUE THREAD

**Issue by Alpha17-2** [Utopia7017/utopia#84]

**Comment by SmartAree** [comment]
If this is for the hactoberfest, can I contribute to this issue??

**Comment by Alpha17-2** [comment]
Yeah !! Sure

**Comment by SmartAree** [comment]
Do you have an onBoarding screen template?

**Comment by Alpha17-2** [comment]
Well I don't have any yet . Are you interested in any other issues ?

**Comment by Alpha17-2** [comment]
Take a look at #58
